#!/usr/bin/env node
import childProcess from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import url from 'node:url';

import { format as formatWithOxfmt, type FormatConfig } from 'oxfmt';

/**
 * Produces the committed, human-auditable snapshots of what each codemod actually outputs for its
 * example fixture, generated by running the real codemod (never hand-written). `--write` (default)
 * regenerates them; `--check` verifies they are still in sync without touching them, so
 * `pnpm quality` catches a fixture change that wasn't followed by `pnpm generate:example-snapshot`.
 */

const repositoryRoot = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const cliEntryPath = path.join(repositoryRoot, 'scripts/cli-entry.ts');

/**
 * The jest-to-vitest snapshot sits beside its fixture rather than inside it: the generated Vitest
 * config picks up nested test files, so a snapshot within the project would be collected
 * as tests and fail on relative imports that no longer resolve.
 */
const JEST_TO_VITEST_SNAPSHOT_DIRECTORY = 'example/jest-to-vitest.snapshot';

/** Never copied into the scratch run. */
const UNCOPIED_ENTRIES = new Set(['node_modules', 'package-lock.json']);

type Snapshot = { relativePath: string; content: string };

function fail(message: string): never {
  console.error(`❌ ${message}`);
  process.exit(1);
}

function bannerFor(codemod: string, provenance: string): string {
  return `// GENERATED FILE — DO NOT EDIT BY HAND.
// ${provenance}
// Regenerate with \`pnpm generate:example-snapshot\`; keeping this file in sync is enforced
// by \`pnpm check:example-snapshot\` (part of \`pnpm quality\`).

`;
}

async function format(content: string, filepath: string): Promise<string> {
  const configPath = path.join(repositoryRoot, '.oxfmtrc.json');
  const options: FormatConfig = JSON.parse(await fs.readFile(configPath, 'utf-8'));
  const result = await formatWithOxfmt(filepath, content, options);

  if (result.errors.length > 0) {
    fail(result.errors.map(error => error.message).join('\n'));
  }

  return result.code;
}

async function copyFixture(source: string, destination: string): Promise<void> {
  await fs.mkdir(destination, { recursive: true });
  for (const entry of await fs.readdir(source, { withFileTypes: true })) {
    if (UNCOPIED_ENTRIES.has(entry.name)) {
      continue;
    }

    const from = path.join(source, entry.name);
    const to = path.join(destination, entry.name);
    if (entry.isDirectory()) {
      await copyFixture(from, to);
    } else if (entry.isFile()) {
      await fs.copyFile(from, to);
    }
  }
}

async function listFiles(directory: string, prefix = ''): Promise<Array<string>> {
  const files: Array<string> = [];
  for (const entry of await fs.readdir(directory, { withFileTypes: true })) {
    const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      files.push(...(await listFiles(path.join(directory, entry.name), relativePath)));
    } else if (entry.isFile()) {
      files.push(relativePath);
    }
  }

  return files.sort();
}

async function readIfPresent(filepath: string): Promise<string | undefined> {
  return fs.readFile(filepath, 'utf-8').catch(() => undefined);
}

/**
 * A fixture left in its transformed state would produce a snapshot of a second run, which is not
 * what the file claims to be, and `--check` would then happily agree with it.
 */
function assertFixtureIsPristine(fixtureDirectory: string): void {
  const status = childProcess.spawnSync('git', ['status', '--porcelain', '--', fixtureDirectory], {
    cwd: repositoryRoot,
    encoding: 'utf-8',
  });
  if (status.status !== 0 || status.stdout.trim() === '') {
    return;
  }

  fail(
    `${fixtureDirectory} has uncommitted changes, so the snapshot would capture a second transform run. Restore it with \`git checkout ${fixtureDirectory}\` first.`,
  );
}

function runCodemod(codemod: string, target: string): void {
  const result = childProcess.spawnSync(process.execPath, [cliEntryPath, codemod, target], { stdio: 'inherit' });
  if (result.status !== 0) {
    fail(`running the ${codemod} codemod against a scratch copy failed`);
  }
}

/**
 * Snapshots every file the codemod created or changed. Files it left alone are already readable in
 * the fixture itself, so repeating them would only make the diff harder to read.
 */
async function generateSnapshots(
  codemod: string,
  fixtureDirectory: string,
  snapshotDirectory: string,
): Promise<Array<Snapshot>> {
  assertFixtureIsPristine(fixtureDirectory);

  const fixturePath = path.join(repositoryRoot, fixtureDirectory);
  const scratchDirectory = await fs.mkdtemp(path.join(os.tmpdir(), `${codemod}-snapshot-`));

  try {
    await copyFixture(fixturePath, scratchDirectory);
    runCodemod(codemod, scratchDirectory);

    const snapshots: Array<Snapshot> = [];
    for (const relativePath of await listFiles(scratchDirectory)) {
      const transformed = await fs.readFile(path.join(scratchDirectory, relativePath), 'utf-8');
      if ((await readIfPresent(path.join(fixturePath, relativePath))) === transformed) {
        continue;
      }

      const snapshotPath = path.join(repositoryRoot, snapshotDirectory, relativePath);
      const formatted = await format(transformed, snapshotPath);
      const existed = (await readIfPresent(path.join(fixturePath, relativePath))) != null;
      const provenance = existed
        ? `Produced by running the ${codemod} codemod over ${fixtureDirectory}/${relativePath}.`
        : `Written by the ${codemod} codemod when it is run over ${fixtureDirectory}.`;
      // JSON has nowhere to put a banner; the directory name and CONTRIBUTING carry it instead.
      const banner = relativePath.endsWith('.json') ? '' : bannerFor(codemod, provenance);
      snapshots.push({ relativePath, content: `${banner}${formatted}` });
    }

    return snapshots;
  } finally {
    await fs.rm(scratchDirectory, { recursive: true, force: true });
  }
}

async function generateSingleFileSnapshot(
  codemod: string,
  sourceRelativePath: string,
  snapshotRelativePath: string,
): Promise<Array<Snapshot>> {
  const scratchDirectory = await fs.mkdtemp(path.join(os.tmpdir(), `${codemod}-snapshot-`));

  try {
    const scratchPath = path.join(scratchDirectory, path.basename(sourceRelativePath));
    await fs.copyFile(path.join(repositoryRoot, sourceRelativePath), scratchPath);
    runCodemod(codemod, scratchDirectory);

    const transformed = await fs.readFile(scratchPath, 'utf-8');
    const formatted = await format(transformed, path.join(repositoryRoot, snapshotRelativePath));

    const provenance = `Produced by running the ${codemod} codemod against ${sourceRelativePath}.`;

    return [{ relativePath: snapshotRelativePath, content: `${bannerFor(codemod, provenance)}${formatted}` }];
  } finally {
    await fs.rm(scratchDirectory, { recursive: true, force: true });
  }
}

type SnapshotTarget = { label: string; snapshotRoot: string; snapshots: () => Promise<Array<Snapshot>> };

const TARGETS: Array<SnapshotTarget> = [
  {
    label: 'joi-to-zod',
    snapshotRoot: '.',
    snapshots: () =>
      generateSingleFileSnapshot('joi-to-zod', 'example/joi-to-zod/schemas.ts', 'example/joi-to-zod/schemas.zod.ts'),
  },
  {
    label: 'jest-to-vitest',
    snapshotRoot: JEST_TO_VITEST_SNAPSHOT_DIRECTORY,
    snapshots: () => generateSnapshots('jest-to-vitest', 'example/jest-to-vitest', JEST_TO_VITEST_SNAPSHOT_DIRECTORY),
  },
];

const mode = process.argv.includes('--check') ? 'check' : 'write';

for (const target of TARGETS) {
  const snapshots = await target.snapshots();
  const snapshotRoot = path.join(repositoryRoot, target.snapshotRoot);

  if (mode === 'write') {
    if (target.snapshotRoot !== '.') {
      await fs.rm(snapshotRoot, { recursive: true, force: true });
    }
    for (const { relativePath, content } of snapshots) {
      const destination = path.join(snapshotRoot, relativePath);
      await fs.mkdir(path.dirname(destination), { recursive: true });
      await fs.writeFile(destination, content);
    }
    console.log(`✅ wrote the ${target.label} example snapshot (${snapshots.length} files)`);
    continue;
  }

  const expected = new Set(snapshots.map(snapshot => snapshot.relativePath));
  for (const { relativePath, content } of snapshots) {
    if ((await readIfPresent(path.join(snapshotRoot, relativePath))) !== content) {
      fail(
        `the ${target.label} example snapshot is out of date at ${relativePath}. Run \`pnpm generate:example-snapshot\` and commit the result.`,
      );
    }
  }
  if (target.snapshotRoot !== '.') {
    const committed = await listFiles(snapshotRoot).catch(() => []);
    const extra = committed.filter(relativePath => !expected.has(relativePath));
    if (extra.length > 0) {
      fail(
        `the ${target.label} example snapshot has files the codemod no longer produces: ${extra.join(', ')}. Run \`pnpm generate:example-snapshot\` and commit the result.`,
      );
    }
  }

  console.log(`✅ the ${target.label} example snapshot is in sync`);
}
