#!/usr/bin/env node
import childProcess from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import url from 'node:url';

import prettier from 'prettier';

/**
 * Produces `example/schemas.zod.ts`: a committed, human-auditable snapshot of what the
 * joi-to-zod codemod actually outputs for `example/schemas.ts`, generated by running the real
 * codemod (never hand-written). `--write` (default) regenerates the file; `--check` verifies it
 * is still in sync without touching it, so `yarn quality` can catch a fixture change that wasn't
 * followed by `yarn generate:example-snapshot`.
 */

const repositoryRoot = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const sourcePath = path.join(repositoryRoot, 'example/schemas.ts');
const snapshotPath = path.join(repositoryRoot, 'example/schemas.zod.ts');
const cliEntryPath = path.join(repositoryRoot, 'scripts/cli-entry.ts');

const BANNER = `// GENERATED FILE — DO NOT EDIT BY HAND.
// Produced by running the joi-to-zod codemod against example/schemas.ts.
// Regenerate with \`yarn generate:example-snapshot\`; keeping this file in sync is enforced
// by \`yarn check:example-snapshot\` (part of \`yarn quality\`).

`;

function fail(message: string): never {
  console.error(`❌ ${message}`);
  process.exit(1);
}

async function generateSnapshotContent(): Promise<string> {
  const scratchDirectory = await fs.mkdtemp(path.join(os.tmpdir(), 'joi-to-zod-snapshot-'));

  try {
    const scratchSchemasPath = path.join(scratchDirectory, 'schemas.ts');
    await fs.copyFile(sourcePath, scratchSchemasPath);

    const result = childProcess.spawnSync(process.execPath, [cliEntryPath, 'joi-to-zod', scratchDirectory], {
      stdio: 'inherit',
    });
    if (result.status !== 0) fail('running the joi-to-zod codemod against a scratch copy failed');

    const transformed = await fs.readFile(scratchSchemasPath, 'utf-8');
    const options = await prettier.resolveConfig(snapshotPath);
    const formatted = await prettier.format(transformed, { ...options, filepath: snapshotPath });

    return `${BANNER}${formatted}`;
  } finally {
    await fs.rm(scratchDirectory, { recursive: true, force: true });
  }
}

const mode = process.argv.includes('--check') ? 'check' : 'write';
const generated = await generateSnapshotContent();

if (mode === 'write') {
  await fs.writeFile(snapshotPath, generated);
  console.log('✅ wrote example/schemas.zod.ts');
} else {
  const current = await fs.readFile(snapshotPath, 'utf-8').catch(() => null);
  if (current !== generated) {
    fail(
      'example/schemas.zod.ts is out of sync with example/schemas.ts. Run `yarn generate:example-snapshot` and commit the result.',
    );
  }

  console.log('✅ example/schemas.zod.ts is in sync');
}
